defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./data"
  dataset: "MNIST"
  digits: [0,2,7,8]
  n_classes: 4
  image_shape: 784
  model_name: "mnist_0123_epoch9.pt"
  model_path: "./models/"
  fisher_path: "./fisher_diags/"


models:
  model1: "mnist_0278_epoch9_02"
  model2: "mnist_0278_epoch9_78"

train:
  lr: 0.01
  hidden_dim: 64
  epochs: 10
  step_size: 212
  w_dc: 0
  gamma: 0.1
  momentum: 0.5

  