defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./data"
  dataset: "FashionMNIST"
  classes: [0,1,2,3,4,5,6,7,8,9]
  n_classes: 10
  image_shape: 784
  model_path: "./models/"
  fisher_path: "./fisher_diags/"
  results_path: "./results/"
  plot: True


models:
  model1: "FashionMNIST_0123456789_epoch50"
  model2: "FashionMNIST_0123456789_epoch30"

train:
  lr: 0.01
  hidden_dim: 16
  epochs: 10
  step_size: 212
  w_dc: 0
  gamma: 0.1
  momentum: 0.5

  