defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  data_path: "./data"
  n_classes: 10
  dataset: "MNIST"
  digits: [0,1]
  image_shape: 784

hyperparameters:
  batch_size: 64
  lr: 0.01
  hidden_dim: 256
  n_epochs: 10
  step_size: 212
  w_dc: 0
  gamma: 0.1

  
 
