defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./fisher/data"

  dataset: "MNIST"
  max_samples_train: -1
  max_samples_test: -1

  classes: [0,1,2,3]
  n_classes: 4

  subset_length: 0
  image_shape: 784
  unbalanced: []
  fisher_path: "./fisher/fisher_diags/"
  grad_path: "./fisher/grad_diags/"
  model_path: "./fisher/models/"
  results_path: "./results/"

  fisher_samples: 10000
  plot: False
  permutations: 100
  weight_permutations: 5
  layer_weight_permutation: 0
  m: 500

train:
  lr: 0.01
  hidden_dim: 4
  epochs: 30
  step_size: 212
  weight_decay: 0.01
  gamma: 0.1
  momentum: 0.5
  normalize: True
  fisher_diagonal: True
  fisher_gradients: True
  n_models: 3
  torch_seed: 40
  plot_sample: False
  plot: False

  
 
