defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./data"
  dataset: "MNIST"
  classes: [0,1,2,3]
  n_classes: 4
  image_shape: 784
  unbalanced: []
  fisher_path: "./fisher/fisher_diags/"
  grad_path: "./fisher/grad_diags/"
  model_path: "./fisher/models/"
  permutations: 50
  plot: False

models:
  model0: "model_0"
  model1: "model_1"
  model2: "model_2"


train:
  lr: 0.01
  weight_decay: 0.01
  hidden_dim: 4
  epochs: 50
  step_size: 212
  gamma: 0.1
  momentum: 0.9
  fisher: True
  name: ""
  plot_sample: False
  plot: False
  torch_seed: 30
