defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./data"
  dataset: "MNIST"
  classes: [0,1,2,3]
  n_classes: 5
  image_shape: 784
  unbalanced: []
  fisher_path: "./fisher/fisher_diags/"
  grad_path: "./fisher/grad_diags/"
  model_path: "./fisher/models/"
  perm_path: "./fisher/perms/"

  permutations: 10
  m: 500
  weight_permutations: 50
  layer_weight_permutation: 2
  scaling_perm_min: 1
  scaling_perm_max: 200
  plot: True

models:
  model0: "MNIST_0123_epoch40"
  model1: "MNIST_0123_epoch30"
  model2: "MNIST_0123_epoch20"

train:
  lr: 0.01
  weight_decay: 0.1
  hidden_dim: 4
  epochs: 5
  epochs_perm: 100
  step_size: 212
  gamma: 0.1
  momentum: 0.9
  fisher: True
  name: ""
  plot_sample: False
  plot: False
  torch_seed: 40
