defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./data"
  dataset: "MNIST"
  classes: [0,1,2,3,4,5,6,7,8,9]
  n_classes: 10
  image_shape: 784
  unbalanced: []
  fisher_path: "./src/computed_fishers/"
  grad_path: "./src/computed_gradients/"
  model_path: "./src/models/"
  perm_path: "./src/computed_permutations/"

  m: 200
  permutations: 10
  weight_permutations: 5
  layer_weight_permutation: 2
  scaling_perm_min: 1
  scaling_perm_max: 5
  number_scalations: 5
  plot: False
  grad_samples: 10000
  n_examples: 10000

models:
  model0: "MNIST_0123456789_epoch80"
  model1: "MNIST_0123456789_epoch100"

train:
  initialization: ""
  lr: 0.01
  perm_lr: 0.01
  weight_decay: 0.001
  hidden_dim: 16
  epochs: 100
  epochs_perm: 100000
  step_size: 212
  gamma: 0.1
  momentum: 0.9
  fisher: True
  name: ""
  plot_sample: False
  plot: False
  torch_seed: 40
