defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./data"
  dataset: "MNIST"
  classes: [0,1,2,3,4,5,6,7,8,9]
  n_classes: 10
  image_shape: 784
  unbalanced: []
  fisher_path: "./src/computed_fishers/"
  grad_path: "./src/computed_gradients/"
  model_path: "./src/models/"
  perm_path: "./src/computed_permutations/"

  max_samples_train: -1
  max_samples_test: -1

  m: 500
  maximum: 1000
  permutations: 20
  plot: False
  grad_samples: 10000
  n_examples: 10000

models:
  model0: "MNIST_0123456789_epoch10"
  model1: "MNIST_0123456789_epoch8"

train:
  training: False
  initialization: ""
  lr: 0.01
  perm_lr: 0.01
  weight_decay: 0.001
  hidden_dim: 16
  epochs_perm: 2000 
  step_size: 212
  gamma: 0.1
  momentum: 0.9
  fisher: True
  name: ""
  plot_sample: False
  plot: False
  torch_seed: 40
