defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./data"
  dataset: "SNELSON"
  dimensions: 1
  n_models: 2
  max_samples_train: 0
  max_samples_test: 0
  fisher_path: "./fisher/fisher_diags/"
  grad_path: "./fisher/grad_diags/"
  model_path: "./fisher/models/"
  fisher_samples: 10000

models:
  model1: "MNIST_01_epoch30"
  model2: "MNIST_23_epoch30"

train:
  lr: 0.01
  hidden_dim: 16
  epochs: 50
  step_size: 212
  weight_decay: 0.01
  gamma: 0.1
  momentum: 0.5
  plot_sample: False
  plot: False
  torch_seed: -1

  
 
