defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./data"

  dataset: "SNELSON"
  max_samples_train: -1
  max_samples_test: -1

  dimensions: 1
  fisher_path: "./fisher_diags/"
  grad_path: "./grad_diags/"
  model_path: "./models/"
  fisher_samples: 10000

models:
  model1: "SNELSON_epoch30_1.pt"
  model2: "SNELSON_epoch30_2.pt"
  model3: "SNELSON_epoch30_3.pt"


train:
  lr: 0.01
  hidden_dim: 32
  epochs: 50
  step_size: 212
  weight_decay: 0.01
  gamma: 0.1
  momentum: 0.5
  normalize: True
  fisher_diagonal: True
  fisher_gradients: True
  torch_seed: 30

  name: ""
  plot_sample: False
  plot: True

  
 
