defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./data"

  dataset: "MNIST"
  max_samples_train: -1
  max_samples_test: -1

  classes: [0,1,2,3]
  n_classes: 4

  subset_length: 0
  image_shape: 784
  unbalanced: []
  fisher_path: "./fisher_diags/"
  grad_path: "./grad_diags/"
  model_path: "./models/"
  fisher_samples: 10000

train:
  lr: 0.01
  hidden_dim: 4
  epochs: 30
  step_size: 212
  weight_decay: 0.01
  gamma: 0.1
  momentum: 0.5
  normalize: True
  fisher_diagonal: True
  fisher_gradients: True
  torch_seed: -1

  name: ""
  plot_sample: False
  plot: False

  
 
