defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  batch_size_train: 64
  batch_size_test: 64
  data_path: "./data"

  dataset: "MNIST"
  max_samples_train: -1
  max_samples_test: -1

  classes: [0,1,2,3]
  n_classes: 4

  subset_length: 0
  image_shape: 784
  unbalanced: []
  fisher_path: "./computed_fishers/"
  grad_path: "./computed_grads/"
  perm_path: "./perms/"

  model_path: "./models/"
  fisher_samples: 10000
  weight_permutations: 200
  layer_wp: 2
  permutations: 200
  m: 500

train:
  lr: 0.01
  hidden_dim: 16
  epochs: 40
  epochs_perm: 500
  step_size: 212
  weight_decay: 0.01
  gamma: 0.1
  momentum: 0.5
  normalize: True
  fisher_diagonal: True
  fisher_gradients: True
  weight_permutations: False
  torch_seed: 40

  name: ""
  plot_sample: False
  plot: False

  
 
